import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          EditCompany(),
        ]),
      ),
    );
  }
}

class EditCompany extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 430,
          height: 1364,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0xFFF4F4F4)),
          child: Stack(
            children: [
              Positioned(
                left: 37,
                top: 245,
                child: Container(
                  width: 351,
                  height: 40,
                  decoration: ShapeDecoration(
                    color: Color(0x00C4C4C4),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFF6EBF45)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 320,
                child: Container(
                  width: 351,
                  height: 40,
                  decoration: ShapeDecoration(
                    color: Color(0x00C4C4C4),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFF6EBF45)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 215,
                child: SizedBox(
                  width: 351,
                  child: Text(
                    'Nama Depan',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 290,
                child: SizedBox(
                  width: 351,
                  child: Text(
                    'Nama Belakang',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 47,
                top: 251,
                child: SizedBox(
                  width: 351,
                  child: Text(
                    'Jennie ',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 45,
                top: 328,
                child: SizedBox(
                  width: 351,
                  child: Text(
                    'Aldebaran',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 395,
                child: Container(
                  width: 351,
                  height: 40,
                  decoration: ShapeDecoration(
                    color: Color(0x00C4C4C4),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFF6EBF45)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 365,
                child: SizedBox(
                  width: 351,
                  child: Text(
                    'Posisi',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 45,
                top: 403,
                child: SizedBox(
                  width: 351,
                  child: Text(
                    'Adebaran',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 470,
                child: Container(
                  width: 351,
                  height: 40,
                  decoration: ShapeDecoration(
                    color: Color(0x00C4C4C4),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFF6EBF45)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 440,
                child: SizedBox(
                  width: 351,
                  child: Text(
                    'Nama Perusahaan',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 45,
                top: 478,
                child: SizedBox(
                  width: 351,
                  child: Text(
                    'Adebaran',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 545,
                child: Container(
                  width: 351,
                  height: 40,
                  decoration: ShapeDecoration(
                    color: Color(0x00C4C4C4),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFF6EBF45)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 515,
                child: SizedBox(
                  width: 351,
                  child: Text(
                    'Email Perusahaan',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 45,
                top: 553,
                child: SizedBox(
                  width: 351,
                  child: Text(
                    'Adebaran',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 620,
                child: Container(
                  width: 351,
                  height: 40,
                  decoration: ShapeDecoration(
                    color: Color(0x00C4C4C4),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFF6EBF45)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 590,
                child: SizedBox(
                  width: 351,
                  child: Text(
                    'Kata Sandi Perusahaan',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 45,
                top: 628,
                child: SizedBox(
                  width: 351,
                  child: Text(
                    'Adebaran',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 845,
                child: Container(
                  width: 351,
                  height: 40,
                  decoration: ShapeDecoration(
                    color: Color(0x00C4C4C4),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFF6EBF45)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 815,
                child: SizedBox(
                  width: 351,
                  child: Text(
                    'Kota Perusahaan',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 45,
                top: 853,
                child: SizedBox(
                  width: 351,
                  child: Text(
                    'Adebaran',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 920,
                child: Container(
                  width: 351,
                  height: 40,
                  decoration: ShapeDecoration(
                    color: Color(0x00C4C4C4),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFF6EBF45)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 45,
                top: 928,
                child: SizedBox(
                  width: 351,
                  child: Text(
                    'Adebaran',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 920,
                child: Container(
                  width: 351,
                  height: 40,
                  decoration: ShapeDecoration(
                    color: Color(0x00C4C4C4),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFF6EBF45)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 890,
                child: SizedBox(
                  width: 351,
                  child: Text(
                    'Kecamatan Perusahaan',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 995,
                child: Container(
                  width: 351,
                  height: 40,
                  decoration: ShapeDecoration(
                    color: Color(0x00C4C4C4),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFF6EBF45)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 45,
                top: 1003,
                child: SizedBox(
                  width: 351,
                  child: Text(
                    'Adebaran',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 995,
                child: Container(
                  width: 351,
                  height: 40,
                  decoration: ShapeDecoration(
                    color: Color(0x00C4C4C4),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFF6EBF45)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 965,
                child: SizedBox(
                  width: 351,
                  child: Text(
                    'Kelurahan Perusahaan',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 1070,
                child: Container(
                  width: 351,
                  height: 40,
                  decoration: ShapeDecoration(
                    color: Color(0x00C4C4C4),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFF6EBF45)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 45,
                top: 1078,
                child: SizedBox(
                  width: 351,
                  child: Text(
                    'Adebaran',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 1070,
                child: Container(
                  width: 351,
                  height: 40,
                  decoration: ShapeDecoration(
                    color: Color(0x00C4C4C4),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFF6EBF45)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 1040,
                child: SizedBox(
                  width: 351,
                  child: Text(
                    'Kode Pos Perusahaan',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 1145,
                child: Container(
                  width: 351,
                  height: 40,
                  decoration: ShapeDecoration(
                    color: Color(0x00C4C4C4),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFF6EBF45)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 1115,
                child: SizedBox(
                  width: 351,
                  child: Text(
                    'Lokasi Perusahaan',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 45,
                top: 1153,
                child: SizedBox(
                  width: 351,
                  child: Text(
                    'Adebaran',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 1145,
                child: Container(
                  width: 351,
                  height: 40,
                  decoration: ShapeDecoration(
                    color: Color(0x00C4C4C4),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFF6EBF45)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 695,
                child: Container(
                  width: 351,
                  height: 40,
                  decoration: ShapeDecoration(
                    color: Color(0x00C4C4C4),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFF6EBF45)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 665,
                child: SizedBox(
                  width: 351,
                  child: Text(
                    'Nomor Ponsel Perusahaan',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 45,
                top: 705,
                child: SizedBox(
                  width: 351,
                  child: Text(
                    'Adebaran',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 770,
                child: Container(
                  width: 351,
                  height: 40,
                  decoration: ShapeDecoration(
                    color: Color(0x00C4C4C4),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFF6EBF45)),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 740,
                child: SizedBox(
                  width: 351,
                  child: Text(
                    'Provinsi Perusahaan',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 45,
                top: 778,
                child: SizedBox(
                  width: 351,
                  child: Text(
                    'Adebaran',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 59,
                top: 1215,
                child: Container(
                  width: 283,
                  height: 40,
                  decoration: BoxDecoration(
                    boxShadow: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 10,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 283,
                          height: 40,
                          decoration: ShapeDecoration(
                            color: Color(0xFF6EBF45),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 113,
                        top: 9,
                        child: Text(
                          'Perbarui',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 16,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w700,
                            height: 0,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: -9,
                top: 0,
                child: Container(
                  width: 428,
                  height: 44,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 428,
                          height: 30,
                          child: Stack(children: []),
                        ),
                      ),
                      Positioned(
                        left: 345,
                        top: 16,
                        child: Container(
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              Container(
                                width: 20,
                                height: 14,
                                child: Stack(children: []),
                              ),
                              const SizedBox(width: 4),
                              Container(
                                width: 16,
                                height: 14,
                                child: Stack(children: []),
                              ),
                              const SizedBox(width: 4),
                              Container(
                                width: 25,
                                height: 14,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 2,
                                      top: 3,
                                      child: Container(
                                        width: 19,
                                        height: 8,
                                        decoration: ShapeDecoration(
                                          color: Color(0xFF2B2B2B),
                                          shape: RoundedRectangleBorder(
                                              borderRadius:
                                                  BorderRadius.circular(1)),
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 351,
                        top: 8,
                        child: Container(
                          width: 6,
                          height: 6,
                          child: Stack(children: []),
                        ),
                      ),
                      Positioned(
                        left: 21,
                        top: 12,
                        child: Container(
                          width: 54,
                          height: 21,
                          clipBehavior: Clip.antiAlias,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 11,
                                top: 3,
                                child: Container(
                                  width: 33,
                                  height: 15,
                                  child: Stack(children: []),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 23,
                top: 81,
                child: Container(
                  width: 382,
                  height: 104,
                  decoration: ShapeDecoration(
                    color: Color(0xFF6EBF45),
                    shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(5)),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 10,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 170,
                top: 160,
                child: Text(
                  'Edit Foto',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 16,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 0.05,
                  ),
                ),
              ),
              Positioned(
                left: 176,
                top: 93,
                child: Container(
                  width: 57,
                  height: 57,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 187.94,
                top: 104.34,
                child: Container(
                  width: 32.11,
                  height: 42.74,
                  child: Stack(children: []),
                ),
              ),
              Positioned(
                left: 178,
                top: 95,
                child: Container(
                  width: 53,
                  height: 53,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/53x53"),
                      fit: BoxFit.fill,
                    ),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 63,
                top: 42,
                child: Text(
                  'Profil',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 16,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 1298,
                child: Container(
                  width: 430,
                  height: 68,
                  padding:
                      const EdgeInsets.symmetric(horizontal: 24, vertical: 6),
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(color: Colors.white),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        height: 51,
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Container(
                              width: 38,
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Container(
                                    height: 32,
                                    child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment:
                                          MainAxisAlignment.start,
                                      crossAxisAlignment:
                                          CrossAxisAlignment.start,
                                      children: [
                                        Container(
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment:
                                                MainAxisAlignment.start,
                                            crossAxisAlignment:
                                                CrossAxisAlignment.center,
                                            children: [
                                              Container(
                                                width: 32,
                                                height: 32,
                                                child: Stack(children: []),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            const SizedBox(height: 6),
                            Text(
                              'Beranda',
                              style: TextStyle(
                                color: Color(0xFF6EBF45),
                                fontSize: 12,
                                fontFamily: 'Poppins',
                                fontWeight: FontWeight.w400,
                                height: 0,
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 32),
                      Container(
                        width: 37,
                        height: 56,
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Container(
                              width: 32,
                              height: 32,
                              child: Stack(children: []),
                            ),
                            const SizedBox(height: 6),
                            Text(
                              'Lahan',
                              style: TextStyle(
                                color: Color(0xFF6EBF45),
                                fontSize: 12,
                                fontFamily: 'Poppins',
                                fontWeight: FontWeight.w400,
                                height: 0,
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 32),
                      Container(
                        height: 56,
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.end,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            const SizedBox(height: 6),
                            SizedBox(
                              width: 38,
                              child: Text(
                                'Histori',
                                style: TextStyle(
                                  color: Color(0xFF6EBF45),
                                  fontSize: 12,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w400,
                                  height: 0,
                                ),
                              ),
                            ),
                            const SizedBox(height: 6),
                            Container(
                              width: 48,
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.end,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  const SizedBox(height: 6),
                                  SizedBox(
                                    width: 48,
                                    child: Text(
                                      'Riwayat',
                                      style: TextStyle(
                                        color: Color(0xFF6EBF45),
                                        fontSize: 12,
                                        fontFamily: 'Poppins',
                                        fontWeight: FontWeight.w400,
                                        height: 0,
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 32),
                      Container(
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Container(
                              width: 32,
                              height: 32,
                              child: Stack(children: []),
                            ),
                            const SizedBox(height: 6),
                            Text(
                              'Langganan',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                color: Color(0xFF6EBF45),
                                fontSize: 12,
                                fontFamily: 'Poppins',
                                fontWeight: FontWeight.w400,
                                height: 0,
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 32),
                      Container(
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Container(
                              width: 32,
                              height: 32,
                              child: Stack(children: []),
                            ),
                            const SizedBox(height: 6),
                            Text(
                              'Akun',
                              style: TextStyle(
                                color: Color(0xFF6EBF45),
                                fontSize: 12,
                                fontFamily: 'Poppins',
                                fontWeight: FontWeight.w700,
                                height: 0,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
