import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          DetaiProduk(),
        ]),
      ),
    );
  }
}

class DetaiProduk extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 430,
          height: 1013,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 26,
                top: 44,
                child: Container(
                  width: 379,
                  height: 615,
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Container(
                              height: 29.50,
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  Container(
                                    width: 30,
                                    padding:
                                        const EdgeInsets.symmetric(vertical: 6),
                                    child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment:
                                          MainAxisAlignment.start,
                                      crossAxisAlignment:
                                          CrossAxisAlignment.start,
                                      children: [],
                                    ),
                                  ),
                                  Text(
                                    'Back',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 15,
                                      fontFamily: 'Plus Jakarta Sans',
                                      fontWeight: FontWeight.w500,
                                      height: 0.09,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            const SizedBox(width: 232),
                            Container(
                              padding: const EdgeInsets.symmetric(
                                  horizontal: 1, vertical: 3),
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: -9,
                child: Container(
                  width: 428.78,
                  height: 319,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 428.78,
                          height: 319,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage(
                                  "https://via.placeholder.com/429x319"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 203.53,
                        top: 260,
                        child: Container(
                          width: 22.87,
                          height: 4,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 4.57,
                                  height: 4,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFF121212),
                                    shape: OvalBorder(),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 9.15,
                                top: 0,
                                child: Opacity(
                                  opacity: 0.20,
                                  child: Container(
                                    width: 4.57,
                                    height: 4,
                                    decoration: ShapeDecoration(
                                      color: Color(0xFF121212),
                                      shape: OvalBorder(),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 18.29,
                                top: 0,
                                child: Opacity(
                                  opacity: 0.20,
                                  child: Container(
                                    width: 4.57,
                                    height: 4,
                                    decoration: ShapeDecoration(
                                      color: Color(0xFF121212),
                                      shape: OvalBorder(),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 267,
                child: Container(
                  width: 429,
                  height: 606,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        topLeft: Radius.circular(20),
                        topRight: Radius.circular(20),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 291,
                child: Container(
                  width: 428.78,
                  height: 333,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 179,
                        child: Container(
                          width: 428.78,
                          height: 154,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 149,
                                child: Container(
                                  width: 428.78,
                                  height: 5,
                                  decoration:
                                      BoxDecoration(color: Color(0xFFF1F1F1)),
                                ),
                              ),
                              Positioned(
                                left: 22.87,
                                top: 57,
                                child: SizedBox(
                                  width: 373.89,
                                  child: Text(
                                    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc consectetur velit at massa vehicula, quis fringilla urna gravida.',
                                    style: TextStyle(
                                      color: Color(0xFFAAAAAA),
                                      fontSize: 14,
                                      fontFamily: 'Poppins',
                                      fontWeight: FontWeight.w400,
                                      height: 0.12,
                                      letterSpacing: 0.07,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 19.44,
                                top: 0,
                                child: Container(
                                  width: 305.11,
                                  height: 37,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 90,
                                          height: 37,
                                          padding: const EdgeInsets.symmetric(
                                              horizontal: 12, vertical: 8),
                                          decoration: ShapeDecoration(
                                            color: Color(0x306EBF45),
                                            shape: RoundedRectangleBorder(
                                                borderRadius:
                                                    BorderRadius.circular(8)),
                                          ),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment:
                                                MainAxisAlignment.start,
                                            crossAxisAlignment:
                                                CrossAxisAlignment.start,
                                            children: [
                                              Text(
                                                'Deskripsi',
                                                style: TextStyle(
                                                  color: Color(0xFF6EBF45),
                                                  fontSize: 14,
                                                  fontFamily: 'Poppins',
                                                  fontWeight: FontWeight.w600,
                                                  height: 0,
                                                  letterSpacing: 0.07,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 125.77,
                                        top: 0,
                                        child: Container(
                                          width: 73,
                                          height: 37,
                                          padding: const EdgeInsets.symmetric(
                                              horizontal: 12, vertical: 8),
                                          decoration: ShapeDecoration(
                                            shape: RoundedRectangleBorder(
                                                borderRadius:
                                                    BorderRadius.circular(8)),
                                          ),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment:
                                                MainAxisAlignment.start,
                                            crossAxisAlignment:
                                                CrossAxisAlignment.start,
                                            children: [
                                              Text(
                                                'Produk',
                                                style: TextStyle(
                                                  color: Color(0xFFAAAAAA),
                                                  fontSize: 14,
                                                  fontFamily: 'Poppins',
                                                  fontWeight: FontWeight.w400,
                                                  height: 0,
                                                  letterSpacing: 0.07,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 232.11,
                                        top: 0,
                                        child: Container(
                                          width: 73,
                                          height: 37,
                                          padding: const EdgeInsets.symmetric(
                                              horizontal: 12, vertical: 8),
                                          decoration: ShapeDecoration(
                                            shape: RoundedRectangleBorder(
                                                borderRadius:
                                                    BorderRadius.circular(8)),
                                          ),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment:
                                                MainAxisAlignment.start,
                                            crossAxisAlignment:
                                                CrossAxisAlignment.start,
                                            children: [
                                              Text(
                                                'Ulasan',
                                                style: TextStyle(
                                                  color: Color(0xFFAAAAAA),
                                                  fontSize: 14,
                                                  fontFamily: 'Poppins',
                                                  fontWeight: FontWeight.w400,
                                                  height: 0,
                                                  letterSpacing: 0.07,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 22.87,
                        top: 88,
                        child: Container(
                          width: 383.04,
                          height: 71,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 383.04,
                                  height: 71,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFF9F9F9),
                                    shape: RoundedRectangleBorder(
                                        borderRadius: BorderRadius.circular(8)),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 259.55,
                                top: 19,
                                child: Container(
                                  width: 105.19,
                                  height: 32,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 36.59,
                                          height: 32,
                                          decoration: ShapeDecoration(
                                            image: DecorationImage(
                                              image: NetworkImage(
                                                  "https://via.placeholder.com/37x32"),
                                              fit: BoxFit.fill,
                                            ),
                                            shape: OvalBorder(
                                              side: BorderSide(
                                                  width: 2,
                                                  color: Color(0xFFF9F9F9)),
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 22.87,
                                        top: 0,
                                        child: Container(
                                          width: 36.59,
                                          height: 32,
                                          decoration: ShapeDecoration(
                                            image: DecorationImage(
                                              image: NetworkImage(
                                                  "https://via.placeholder.com/37x32"),
                                              fit: BoxFit.fill,
                                            ),
                                            shape: OvalBorder(
                                              side: BorderSide(
                                                  width: 2,
                                                  color: Color(0xFFF9F9F9)),
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 45.74,
                                        top: 0,
                                        child: Container(
                                          width: 36.59,
                                          height: 32,
                                          decoration: ShapeDecoration(
                                            image: DecorationImage(
                                              image: NetworkImage(
                                                  "https://via.placeholder.com/37x32"),
                                              fit: BoxFit.fill,
                                            ),
                                            shape: OvalBorder(
                                              side: BorderSide(
                                                  width: 2,
                                                  color: Color(0xFFF9F9F9)),
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 68.60,
                                        top: 0,
                                        child: Container(
                                          width: 36.59,
                                          height: 32,
                                          decoration: ShapeDecoration(
                                            image: DecorationImage(
                                              image: NetworkImage(
                                                  "https://via.placeholder.com/37x32"),
                                              fit: BoxFit.fill,
                                            ),
                                            shape: OvalBorder(
                                              side: BorderSide(
                                                  width: 2,
                                                  color: Color(0xFFF9F9F9)),
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 18.29,
                                top: 16,
                                child: Container(
                                  width: 144.07,
                                  height: 39,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 24,
                                        child: Container(
                                          width: 81,
                                          height: 15,
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment:
                                                MainAxisAlignment.start,
                                            crossAxisAlignment:
                                                CrossAxisAlignment.center,
                                            children: [
                                              Text(
                                                '98 Reviews',
                                                style: TextStyle(
                                                  color: Color(0xFFAAAAAA),
                                                  fontSize: 12,
                                                  fontFamily: 'Poppins',
                                                  fontWeight: FontWeight.w400,
                                                  height: 0.10,
                                                  letterSpacing: 0.06,
                                                ),
                                              ),
                                              const SizedBox(width: 2),
                                              Container(
                                                width: 12,
                                                height: 12,
                                                child: Stack(children: []),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 144.07,
                                          height: 15.69,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 123.49,
                                                top: 0.69,
                                                child: SizedBox(
                                                  width: 20.58,
                                                  child: Text(
                                                    '4.6',
                                                    style: TextStyle(
                                                      color: Color(0xFF121212),
                                                      fontSize: 12,
                                                      fontFamily: 'Poppins',
                                                      fontWeight:
                                                          FontWeight.w400,
                                                      height: 0.10,
                                                      letterSpacing: 0.06,
                                                    ),
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 109.77,
                                                  height: 14.97,
                                                  child: Stack(children: []),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 309.86,
                        top: 41,
                        child: Container(
                          width: 96.05,
                          height: 24,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 27.44,
                                  height: 24,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 1.43,
                                        top: 1.25,
                                        child: Container(
                                          width: 24.58,
                                          height: 21.50,
                                          decoration: BoxDecoration(
                                            image: DecorationImage(
                                              image: NetworkImage(
                                                  "https://via.placeholder.com/25x21"),
                                              fit: BoxFit.fill,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 45.74,
                                top: 5,
                                child: SizedBox(
                                  width: 4.57,
                                  child: Text(
                                    '1',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Color(0xFF121212),
                                      fontSize: 12,
                                      fontFamily: 'Poppins',
                                      fontWeight: FontWeight.w400,
                                      height: 0.10,
                                      letterSpacing: 0.06,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 68.60,
                                top: 0,
                                child: Container(
                                  width: 27.44,
                                  height: 24,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 1.43,
                                        top: 1.25,
                                        child: Container(
                                          width: 24.58,
                                          height: 21.50,
                                          decoration: BoxDecoration(
                                            image: DecorationImage(
                                              image: NetworkImage(
                                                  "https://via.placeholder.com/25x21"),
                                              fit: BoxFit.fill,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 22.87,
                        top: 0,
                        child: Container(
                          width: 254.98,
                          height: 68,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: SizedBox(
                                  width: 254.98,
                                  child: Text(
                                    'Alat XXXX',
                                    style: TextStyle(
                                      color: Color(0xFF121212),
                                      fontSize: 20,
                                      fontFamily: 'Poppins',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                      letterSpacing: 0.10,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0.13,
                                top: 38,
                                child: SizedBox(
                                  width: 155,
                                  child: Text(
                                    'Rp. 6.000.000',
                                    style: TextStyle(
                                      color: Color(0xFF6EBF45),
                                      fontSize: 20,
                                      fontFamily: 'Poppins',
                                      fontWeight: FontWeight.w600,
                                      height: 0,
                                      letterSpacing: 0.10,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 17,
                top: 650,
                child: Container(
                  height: 256,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 48,
                        child: Container(
                          width: 575.13,
                          height: 208,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 395.62,
                                top: 0,
                                child: Container(
                                  width: 179.51,
                                  height: 208,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 53,
                                        child: Container(
                                          width: 179.51,
                                          height: 155,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 179.51,
                                                  height: 155,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.white,
                                                    shape:
                                                        RoundedRectangleBorder(
                                                            borderRadius:
                                                                BorderRadius
                                                                    .circular(
                                                                        8)),
                                                    shadows: [
                                                      BoxShadow(
                                                        color:
                                                            Color(0x19202020),
                                                        blurRadius: 50,
                                                        offset: Offset(0, 4),
                                                        spreadRadius: -5,
                                                      )
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 9.15,
                                                top: 104,
                                                child: Container(
                                                  width: 84.61,
                                                  height: 43,
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0.24,
                                                        top: 22,
                                                        child: SizedBox(
                                                          width: 84,
                                                          child: Text(
                                                            'Rp 3-.000',
                                                            style: TextStyle(
                                                              color: Color(
                                                                  0xFF121212),
                                                              fontSize: 14,
                                                              fontFamily:
                                                                  'Poppins',
                                                              fontWeight:
                                                                  FontWeight
                                                                      .w600,
                                                              height: 0,
                                                              letterSpacing:
                                                                  0.07,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: SizedBox(
                                                          width: 84.61,
                                                          child: Text(
                                                            'Alat XXX',
                                                            style: TextStyle(
                                                              color: Color(
                                                                  0xFFAAAAAA),
                                                              fontSize: 12,
                                                              fontFamily:
                                                                  'Poppins',
                                                              fontWeight:
                                                                  FontWeight
                                                                      .w400,
                                                              height: 0,
                                                              letterSpacing:
                                                                  0.06,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 9.15,
                                        top: 0,
                                        child: Container(
                                          width: 161.22,
                                          height: 149,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 161.22,
                                                  height: 149,
                                                  decoration: ShapeDecoration(
                                                    image: DecorationImage(
                                                      image: NetworkImage(
                                                          "https://via.placeholder.com/161x149"),
                                                      fit: BoxFit.fill,
                                                    ),
                                                    shape:
                                                        RoundedRectangleBorder(
                                                            borderRadius:
                                                                BorderRadius
                                                                    .circular(
                                                                        8)),
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 122.34,
                                                top: 8,
                                                child: Container(
                                                  width: 29.73,
                                                  height: 26,
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: Container(
                                                          width: 29.73,
                                                          height: 26,
                                                          decoration:
                                                              ShapeDecoration(
                                                            color: Colors.white,
                                                            shape: OvalBorder(),
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 8,
                                                        top: 7,
                                                        child: Container(
                                                          width: 13.72,
                                                          height: 12,
                                                          child: Stack(
                                                              children: []),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 179.51,
                                  height: 208,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 53,
                                        child: Container(
                                          width: 179.51,
                                          height: 155,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 179.51,
                                                  height: 155,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.white,
                                                    shape:
                                                        RoundedRectangleBorder(
                                                            borderRadius:
                                                                BorderRadius
                                                                    .circular(
                                                                        8)),
                                                    shadows: [
                                                      BoxShadow(
                                                        color:
                                                            Color(0x19202020),
                                                        blurRadius: 50,
                                                        offset: Offset(0, 4),
                                                        spreadRadius: -5,
                                                      )
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 9,
                                                top: 104,
                                                child: Container(
                                                  width: 87,
                                                  height: 43,
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 22,
                                                        child: SizedBox(
                                                          width: 87,
                                                          child: Text(
                                                            'Rp 600.000',
                                                            style: TextStyle(
                                                              color: Color(
                                                                  0xFF121212),
                                                              fontSize: 14,
                                                              fontFamily:
                                                                  'Poppins',
                                                              fontWeight:
                                                                  FontWeight
                                                                      .w600,
                                                              height: 0,
                                                              letterSpacing:
                                                                  0.07,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 0.13,
                                                        top: 0,
                                                        child: SizedBox(
                                                          width: 81.39,
                                                          child: Text(
                                                            'Alat XXX',
                                                            style: TextStyle(
                                                              color: Color(
                                                                  0xFFAAAAAA),
                                                              fontSize: 12,
                                                              fontFamily:
                                                                  'Poppins',
                                                              fontWeight:
                                                                  FontWeight
                                                                      .w400,
                                                              height: 0,
                                                              letterSpacing:
                                                                  0.06,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 9.15,
                                        top: 0,
                                        child: Container(
                                          width: 161.22,
                                          height: 149,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 161.22,
                                                  height: 149,
                                                  decoration: ShapeDecoration(
                                                    image: DecorationImage(
                                                      image: NetworkImage(
                                                          "https://via.placeholder.com/161x149"),
                                                      fit: BoxFit.fill,
                                                    ),
                                                    shape:
                                                        RoundedRectangleBorder(
                                                            borderRadius:
                                                                BorderRadius
                                                                    .circular(
                                                                        8)),
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 122.34,
                                                top: 8,
                                                child: Container(
                                                  width: 29.73,
                                                  height: 26,
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: Container(
                                                          width: 29.73,
                                                          height: 26,
                                                          decoration:
                                                              ShapeDecoration(
                                                            color: Colors.white,
                                                            shape: OvalBorder(),
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 8,
                                                        top: 7,
                                                        child: Container(
                                                          width: 13.72,
                                                          height: 12,
                                                          child: Stack(
                                                              children: []),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 197.81,
                                top: 0,
                                child: Container(
                                  width: 179.51,
                                  height: 208,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 53,
                                        child: Container(
                                          width: 179.51,
                                          height: 155,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 179.51,
                                                  height: 155,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.white,
                                                    shape:
                                                        RoundedRectangleBorder(
                                                            borderRadius:
                                                                BorderRadius
                                                                    .circular(
                                                                        8)),
                                                    shadows: [
                                                      BoxShadow(
                                                        color:
                                                            Color(0x14202020),
                                                        blurRadius: 15,
                                                        offset: Offset(0, 6),
                                                        spreadRadius: 0,
                                                      )
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 9.15,
                                                top: 104,
                                                child: Container(
                                                  width: 93.76,
                                                  height: 43,
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 22,
                                                        child: Container(
                                                          width: 55,
                                                          height: 21,
                                                          child: Row(
                                                            mainAxisSize:
                                                                MainAxisSize
                                                                    .min,
                                                            mainAxisAlignment:
                                                                MainAxisAlignment
                                                                    .start,
                                                            crossAxisAlignment:
                                                                CrossAxisAlignment
                                                                    .center,
                                                            children: [
                                                              Text(
                                                                '\$99',
                                                                style:
                                                                    TextStyle(
                                                                  color: Color(
                                                                      0xFFAAAAAA),
                                                                  fontSize: 12,
                                                                  fontFamily:
                                                                      'Poppins',
                                                                  fontWeight:
                                                                      FontWeight
                                                                          .w400,
                                                                  height: 0,
                                                                  letterSpacing:
                                                                      0.06,
                                                                ),
                                                              ),
                                                              const SizedBox(
                                                                  width: 4),
                                                              Text(
                                                                '\$49',
                                                                style:
                                                                    TextStyle(
                                                                  color: Color(
                                                                      0xFFE24646),
                                                                  fontSize: 14,
                                                                  fontFamily:
                                                                      'Poppins',
                                                                  fontWeight:
                                                                      FontWeight
                                                                          .w600,
                                                                  height: 0,
                                                                  letterSpacing:
                                                                      0.07,
                                                                ),
                                                              ),
                                                            ],
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: SizedBox(
                                                          width: 93.76,
                                                          child: Text(
                                                            'Ödmjuk chair',
                                                            style: TextStyle(
                                                              color: Color(
                                                                  0xFFAAAAAA),
                                                              fontSize: 12,
                                                              fontFamily:
                                                                  'Poppins',
                                                              fontWeight:
                                                                  FontWeight
                                                                      .w400,
                                                              height: 0,
                                                              letterSpacing:
                                                                  0.06,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 9.15,
                                        top: 0,
                                        child: Container(
                                          width: 161.22,
                                          height: 149,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 161.22,
                                                  height: 149,
                                                  decoration: ShapeDecoration(
                                                    image: DecorationImage(
                                                      image: NetworkImage(
                                                          "https://via.placeholder.com/161x149"),
                                                      fit: BoxFit.fill,
                                                    ),
                                                    shape:
                                                        RoundedRectangleBorder(
                                                            borderRadius:
                                                                BorderRadius
                                                                    .circular(
                                                                        8)),
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 122.34,
                                                top: 8,
                                                child: Container(
                                                  width: 29.73,
                                                  height: 26,
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: Container(
                                                          width: 29.73,
                                                          height: 26,
                                                          decoration:
                                                              ShapeDecoration(
                                                            color: Colors.white,
                                                            shape: OvalBorder(),
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 8,
                                                        top: 7,
                                                        child: Container(
                                                          width: 13.72,
                                                          height: 12,
                                                          child: Stack(
                                                              children: []),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 197.81,
                                top: 0,
                                child: Container(
                                  width: 179.51,
                                  height: 208,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 53,
                                        child: Container(
                                          width: 179.51,
                                          height: 155,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 179.51,
                                                  height: 155,
                                                  decoration: ShapeDecoration(
                                                    color: Colors.white,
                                                    shape:
                                                        RoundedRectangleBorder(
                                                            borderRadius:
                                                                BorderRadius
                                                                    .circular(
                                                                        8)),
                                                    shadows: [
                                                      BoxShadow(
                                                        color:
                                                            Color(0x19202020),
                                                        blurRadius: 50,
                                                        offset: Offset(0, 4),
                                                        spreadRadius: -5,
                                                      )
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 9.15,
                                                top: 104,
                                                child: Container(
                                                  width: 94.90,
                                                  height: 43,
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0.04,
                                                        top: 22,
                                                        child: SizedBox(
                                                          width: 81,
                                                          child: Text(
                                                            'RP 700.000',
                                                            style: TextStyle(
                                                              color: Color(
                                                                  0xFF121212),
                                                              fontSize: 14,
                                                              fontFamily:
                                                                  'Poppins',
                                                              fontWeight:
                                                                  FontWeight
                                                                      .w600,
                                                              height: 0,
                                                              letterSpacing:
                                                                  0.07,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: SizedBox(
                                                          width: 94.90,
                                                          child: Text(
                                                            'Alat XXX',
                                                            style: TextStyle(
                                                              color: Color(
                                                                  0xFFAAAAAA),
                                                              fontSize: 12,
                                                              fontFamily:
                                                                  'Poppins',
                                                              fontWeight:
                                                                  FontWeight
                                                                      .w400,
                                                              height: 0,
                                                              letterSpacing:
                                                                  0.06,
                                                            ),
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 9.15,
                                        top: 0,
                                        child: Container(
                                          width: 161.22,
                                          height: 149,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 161.22,
                                                  height: 149,
                                                  decoration: ShapeDecoration(
                                                    image: DecorationImage(
                                                      image: NetworkImage(
                                                          "https://via.placeholder.com/161x149"),
                                                      fit: BoxFit.fill,
                                                    ),
                                                    shape:
                                                        RoundedRectangleBorder(
                                                            borderRadius:
                                                                BorderRadius
                                                                    .circular(
                                                                        8)),
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 122.34,
                                                top: 8,
                                                child: Container(
                                                  width: 29.73,
                                                  height: 26,
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: Container(
                                                          width: 29.73,
                                                          height: 26,
                                                          decoration:
                                                              ShapeDecoration(
                                                            color: Colors.white,
                                                            shape: OvalBorder(),
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 8,
                                                        top: 7,
                                                        child: Container(
                                                          width: 13.72,
                                                          height: 12,
                                                          child: Stack(
                                                              children: []),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 155.50,
                          child: Text(
                            'Produk',
                            style: TextStyle(
                              color: Color(0xFF121212),
                              fontSize: 16,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w600,
                              height: 0,
                              letterSpacing: 0.08,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 932,
                child: Container(
                  width: 428.78,
                  height: 90,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 428.78,
                          height: 90,
                          decoration: BoxDecoration(color: Colors.white),
                        ),
                      ),
                      Positioned(
                        left: 82.32,
                        top: 16,
                        child: Container(
                          width: 323.58,
                          height: 40,
                          padding: const EdgeInsets.all(10),
                          decoration: ShapeDecoration(
                            color: Color(0xFF6EBF45),
                            shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(8)),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Expanded(
                                child: SizedBox(
                                  child: Text(
                                    'Tambahkan ke keranjang',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 14,
                                      fontFamily: 'Poppins',
                                      fontWeight: FontWeight.w600,
                                      height: 0.10,
                                      letterSpacing: 0.07,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 22.87,
                        top: 16,
                        child: Container(
                          width: 45.74,
                          height: 40,
                          padding: const EdgeInsets.all(10),
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                  width: 1, color: Color(0xFFAAAAAA)),
                              borderRadius: BorderRadius.circular(8),
                            ),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Container(
                                width: 20,
                                height: 20,
                                child: Stack(children: []),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 428.78,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: Color(0xFFDEDEDE),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: -9,
                child: Container(
                  width: 428.78,
                  height: 108,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 428.78,
                          height: 108,
                          decoration: BoxDecoration(
                            gradient: LinearGradient(
                              begin: Alignment(-0.00, -1.00),
                              end: Alignment(0, 1),
                              colors: [
                                Colors.black,
                                Colors.black.withOpacity(0)
                              ],
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 369.32,
                        top: 56,
                        child: Container(
                          width: 36.59,
                          height: 32,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 6.86,
                                top: 6,
                                child: Container(
                                  width: 22.87,
                                  height: 20,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                          "https://via.placeholder.com/23x20"),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 22.87,
                        top: 56,
                        child: Container(
                          width: 36.59,
                          height: 32,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 36.59,
                                  height: 32,
                                  decoration: ShapeDecoration(
                                    color: Color(0x7FBFB4AA),
                                    shape: RoundedRectangleBorder(
                                        borderRadius: BorderRadius.circular(8)),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: -9,
                child: Container(
                  height: 44,
                  padding: const EdgeInsets.only(
                    top: 13,
                    left: 37.16,
                    right: 16.40,
                    bottom: 13,
                  ),
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.end,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: 375.43,
                        height: 18,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 348.17,
                              top: 4.83,
                              child: Container(
                                width: 27.26,
                                height: 10.33,
                                child: Stack(children: []),
                              ),
                            ),
                            Positioned(
                              left: 0,
                              top: 0,
                              child: SizedBox(
                                width: 37.75,
                                child: Text(
                                  '9:41',
                                  style: TextStyle(
                                    color: Colors.white,
                                    fontSize: 15,
                                    fontFamily: 'Lato',
                                    fontWeight: FontWeight.w900,
                                    height: 0,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
